// #141 D5 — the verdict composed. The gate script and the diversity instrument.
//
//   cd tools/proto
//   NODE_PATH=../node_modules node verdict-proto.mjs --baseline
//
// §7.3's pin is "across the 80-world calibration sweep at defaults (ep=10), no
// verdict class > 40%, >=6 classes present". The class space already exists (B11,
// #133): gap x floor gives six cells, qualified by growth into eighteen. What has
// never been measured is whether the eighteen are REACHED. Measure before authoring.
import { setupEngine } from "../lib.mjs";
const E = await setupEngine();
const arg = (k, d) => { const i = process.argv.indexOf("--" + k); return i > 0 ? process.argv[i + 1] : d; };
const has = (k) => process.argv.includes("--" + k);
const N = Number(arg("n", "80"));
const of_ = (h) => { const S = E.parseHash(h); const r = E.buildTopology(S), g = E.buildGeology(r, S);
  const m = E.applyAttributes(r, S, g); return { F: E.getFindings(m), m, S }; };

const cls = new Map(), cells = new Map(), growths = new Map();
for (let i = 0; i < N; i++) {
  const { F } = of_(`#seed=v5-${i}&regions=24&ep=10`);
  const v = F.verdict;
  cls.set(v.class, (cls.get(v.class) || 0) + 1);
  cells.set(v.cell, (cells.get(v.cell) || 0) + 1);
  growths.set(v.growth, (growths.get(v.growth) || 0) + 1);
}
const show = (label, m, total) => {
  console.log(`\n## ${label} — ${m.size} present`);
  for (const [k, n] of [...m].sort((a, b) => b[1] - a[1]))
    console.log(`  ${String(n).padStart(3)}  ${(100 * n / total).toFixed(0).padStart(3)}%  ${k}`);
};
console.log(`# #141 — the verdict space as it stands, ${N} worlds at defaults (regions=24, ep=10)`);
show("full class (cell x growth)", cls, N);
show("cell (gap x floor)", cells, N);
show("growth qualifier", growths, N);
const top = [...cls.values()].sort((a, b) => b - a)[0];
console.log(`\n§7.3: ${cls.size} classes present (need >=6), largest ${(100 * top / N).toFixed(0)}% (need <40%) — ` +
  (cls.size >= 6 && top / N < 0.40 ? "PASS" : "**MISS**"));
console.log(`Of the 18 the space can express, ${cls.size} are reached and ${18 - cls.size} are not.`);

// --sample writes the committed sample: one verdict per cell the sweep reaches.
if (process.argv.includes("--sample")) {
  const seen = new Map();
  for (let i = 0; i < 400 && seen.size < 6; i++) {
    const S = E.parseHash(`#seed=v5s-${i}&regions=24&ep=10`);
    const r = E.buildTopology(S), g = E.buildGeology(r, S);
    const m = E.applyAttributes(r, S, g);
    const cell = E.getFindings(m).verdict.cell;
    if (!seen.has(cell)) seen.set(cell, { seed: `v5s-${i}`, v: E.composeVerdict(m, S), m });
  }
  let md = `# The verdict, composed — D5 sample (#141)\n\n`;
  md += `Generated by \`tools/proto/verdict-proto.mjs --sample\` against the shipping\n`;
  md += `\`composeVerdict\`. One world per cell of §3.5's matrix that the sweep reaches.\n`;
  md += `The judge register is on the SPELLED law: no numeral appears, and every\n`;
  md += `quantity behind a number-word is audited against the export.\n`;
  for (const [cell, x] of seen)
    md += `\n---\n\n## \`${cell}\` — seed \`${x.seed}\`\n\n${x.v.text}\n`;
  md += `\n---\n\n## \`unequal growth\` — not reached\n\n`;
  md += `The sixth cell, a widening gap over a RISING floor, appears in 0 of 400 worlds\n`;
  md += `at defaults and 2 of 336 across the knob space. In this model a gap that widens\n`;
  md += `takes the floor down with it. The prose for the cell is authored and the suite\n`;
  md += `asserts the absence, so a later mechanism that makes it reachable turns the\n`;
  md += `check red rather than passing unnoticed.\n`;
  console.log(md);
}

// --floor: the survivorship question behind the verdict's second axis. The floor is
// the poorest tenth of the regions STILL STANDING, taken at both ends on that same
// set, which is the right way to measure a change and the wrong way to be quiet
// about: a realm that abandoned its poorest ground shows a risen floor because that
// ground stopped being counted. This measures how often the sign flips when the
// founding tenth is taken over the FOUNDING set instead. The measure is unchanged;
// the judge names the abandonment whenever the floor rose and any settlement left.
if (has("floor")) {
  const p10 = (a) => { const t = a.slice().sort((x, y) => x - y); return t.length ? t[Math.floor(0.1 * (t.length - 1))] : 0; };
  let rose = 0, withDeaths = 0, flips = 0; const eg = [];
  const M = 200;
  for (let i = 0; i < M; i++) {
    const S = E.parseHash(`#seed=fl-${i}&regions=24&ep=10`);
    const r = E.buildTopology(S), g = E.buildGeology(r, S);
    const m = E.applyAttributes(r, S, g), F = E.getFindings(m);
    if (F.floor.p10 - F.floor.p10_t0 <= 0) continue;
    rose++;
    const now = m.regions.filter(x => x.settled);
    const founded = m.regions.filter(x => x.wealthT0 > 0 || x.settled);
    const died = founded.length - now.length;
    if (died > 0) withDeaths++;
    if (p10(now.map(x => x.wealth)) <= p10(founded.map(x => x.wealthT0))) {
      flips++;
      if (eg.length < 3) eg.push(`fl-${i}: ${F.floor.p10_t0}->${F.floor.p10} on survivors, ${died} settlements gone`);
    }
  }
  console.log(`# ${M} worlds at defaults`);
  console.log(`  the floor rose in ${rose}`);
  console.log(`  ...of those, ${withDeaths} lost at least one settled region`);
  console.log(`  ...and in ${flips} the rise DISAPPEARS against the founding set`);
  for (const e of eg) console.log(`   ${e}`);
  process.exit(0);
}

// --rate: how rare is `unequal growth` (a widening gap over a RISING floor)? Earlier
// statements in this repo were bounds from single seed families, and two of them
// overstated. This measures a rate the docs can quote.
if (has("rate")) {
  const FAMS = ["v5", "v5s", "hunt", "atlas", "ir", "vd", "fl", "vp"];
const PER = 150;
  let n = 0, widened = 0, widenedRose = 0;
  const cells = new Map(), hits = [];
for (const f of FAMS) for (let i = 0; i < PER; i++) {
  const { F } = of_(`#seed=${f}-${i}&regions=24&ep=10`); n++;
  cells.set(F.verdict.cell, (cells.get(F.verdict.cell) || 0) + 1);
  if (F.verdict.gap === "widened") { widened++; if (F.verdict.floor === "rose") widenedRose++; }
  if (F.verdict.cell === "unequal growth") hits.push(`${f}-${i}`);
}
  console.log(`# ${n} worlds at defaults (regions=24, ep=10) across ${FAMS.length} seed families`);
for (const [c, k] of [...cells].sort((a, b) => b[1] - a[1]))
  console.log(`  ${String(k).padStart(5)}  ${(100 * k / n).toFixed(2).padStart(6)}%  ${c}`);
console.log(`\nunequal growth: ${hits.length}/${n} = ${(100 * hits.length / n).toFixed(2)}%  (1 in ${hits.length ? Math.round(n / hits.length) : "∞"})`);
console.log(`  seeds: ${hits.slice(0, 8).join(", ") || "none"}`);
console.log(`\nthe mechanism: of ${widened} worlds whose gap widened, ${widenedRose} also raised the floor`);
console.log(`  = ${(100 * widenedRose / Math.max(1, widened)).toFixed(1)}%, about 1 in ${widenedRose ? Math.round(widened / widenedRose) : "∞"}`);

  process.exit(0);
}
