// #141 D5 — the verdict composed. The gate script and the diversity instrument.
//
//   cd tools/proto
//   NODE_PATH=../node_modules node verdict-proto.mjs --baseline
//
// §7.3's pin is "across the 80-world calibration sweep at defaults (ep=10), no
// verdict class > 40%, >=6 classes present". The class space already exists (B11,
// #133): gap x floor gives six cells, qualified by growth into eighteen. What has
// never been measured is whether the eighteen are REACHED. Measure before authoring.
import { setupEngine } from "../lib.mjs";
const E = await setupEngine();
const arg = (k, d) => { const i = process.argv.indexOf("--" + k); return i > 0 ? process.argv[i + 1] : d; };
const N = Number(arg("n", "80"));
const of_ = (h) => { const S = E.parseHash(h); const r = E.buildTopology(S), g = E.buildGeology(r, S);
  const m = E.applyAttributes(r, S, g); return { F: E.getFindings(m), m, S }; };

const cls = new Map(), cells = new Map(), growths = new Map();
for (let i = 0; i < N; i++) {
  const { F } = of_(`#seed=v5-${i}&regions=24&ep=10`);
  const v = F.verdict;
  cls.set(v.class, (cls.get(v.class) || 0) + 1);
  cells.set(v.cell, (cells.get(v.cell) || 0) + 1);
  growths.set(v.growth, (growths.get(v.growth) || 0) + 1);
}
const show = (label, m, total) => {
  console.log(`\n## ${label} — ${m.size} present`);
  for (const [k, n] of [...m].sort((a, b) => b[1] - a[1]))
    console.log(`  ${String(n).padStart(3)}  ${(100 * n / total).toFixed(0).padStart(3)}%  ${k}`);
};
console.log(`# #141 — the verdict space as it stands, ${N} worlds at defaults (regions=24, ep=10)`);
show("full class (cell x growth)", cls, N);
show("cell (gap x floor)", cells, N);
show("growth qualifier", growths, N);
const top = [...cls.values()].sort((a, b) => b - a)[0];
console.log(`\n§7.3: ${cls.size} classes present (need >=6), largest ${(100 * top / N).toFixed(0)}% (need <40%) — ` +
  (cls.size >= 6 && top / N < 0.40 ? "PASS" : "**MISS**"));
console.log(`Of the 18 the space can express, ${cls.size} are reached and ${18 - cls.size} are not.`);

// --sample writes the committed sample: one verdict per cell the sweep reaches.
if (process.argv.includes("--sample")) {
  const seen = new Map();
  for (let i = 0; i < 400 && seen.size < 6; i++) {
    const S = E.parseHash(`#seed=v5s-${i}&regions=24&ep=10`);
    const r = E.buildTopology(S), g = E.buildGeology(r, S);
    const m = E.applyAttributes(r, S, g);
    const cell = E.getFindings(m).verdict.cell;
    if (!seen.has(cell)) seen.set(cell, { seed: `v5s-${i}`, v: E.composeVerdict(m, S), m });
  }
  let md = `# The verdict, composed — D5 sample (#141)\n\n`;
  md += `Generated by \`tools/proto/verdict-proto.mjs --sample\` against the shipping\n`;
  md += `\`composeVerdict\`. One world per cell of §3.5's matrix that the sweep reaches.\n`;
  md += `The judge register is on the SPELLED law: no numeral appears, and every\n`;
  md += `quantity behind a number-word is audited against the export.\n`;
  for (const [cell, x] of seen)
    md += `\n---\n\n## \`${cell}\` — seed \`${x.seed}\`\n\n${x.v.text}\n`;
  md += `\n---\n\n## \`unequal growth\` — not reached\n\n`;
  md += `The sixth cell, a widening gap over a RISING floor, appears in 0 of 400 worlds\n`;
  md += `at defaults and 2 of 336 across the knob space. In this model a gap that widens\n`;
  md += `takes the floor down with it. The prose for the cell is authored and the suite\n`;
  md += `asserts the absence, so a later mechanism that makes it reachable turns the\n`;
  md += `check red rather than passing unnoticed.\n`;
  console.log(md);
}
